### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by Exponential-Workload** [Sellix/node-sdk#1]
I'd like to see Typescript Definitions sometime soon. This is mainly so I can have intelisense and so this error disappears:
![image](https://user-images.githubusercontent.com/90570076/166150962-1ada9506-40d0-418d-866a-40f9cbcfc615.png)

**Comment by MrlolDev** [comment]
any update¿

**Comment by danieleServadei** [comment]
we will not be adding TS in the near future
